version: "3.8"

services:

  public:
    build: .
    command: bash -c "uvicorn public:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./:/app
    ports:
      - 8000:8000

  private:
    build: .
    command: bash -c "uvicorn private:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./:/app
    ports:
      - 8001:8000
